{
  pkgs,
  lib,
  ...
}: {
  programs.hyprpanel = {
    enable = true;
  };
  # This looks ugly,i hope it works at least
  home.file.".config/hyprpanel/config1.json" = {
    text = ''
          {
        "bar.customModules.updates.pollingInterval": 1439000,
        "theme.bar.buttons.workspaces.enableBorder": false,
        "bar.workspaces.show_icons": false,
        "theme.bar.buttons.windowtitle.enableBorder": false,
        "theme.osd.enable": true,
        "menus.clock.time.military": true,
        "menus.clock.time.hideSeconds": false,
        "bar.autoHide": "never",
        "theme.bar.layer": "top",
        "theme.matugen": true,
        "theme.bar.menus.menu.notifications.scrollbar.color": "#c4a7e7",
        "theme.bar.menus.menu.notifications.pager.label": "#56526e",
        "theme.bar.menus.menu.notifications.pager.button": "#c4a7e7",
        "theme.bar.menus.menu.notifications.pager.background": "#232136",
        "theme.bar.menus.menu.notifications.switch.puck": "#393552",
        "theme.bar.menus.menu.notifications.switch.disabled": "#2a273f",
        "theme.bar.menus.menu.notifications.switch.enabled": "#c4a7e7",
        "theme.bar.menus.menu.notifications.clear": "#eb6f92",
        "theme.bar.menus.menu.notifications.switch_divider": "#393552",
        "theme.bar.menus.menu.notifications.border": "#2a273f",
        "theme.bar.menus.menu.notifications.card": "#2a283e",
        "theme.bar.menus.menu.notifications.background": "#232136",
        "theme.bar.menus.menu.notifications.no_notifications_label": "#2a273f",
        "theme.bar.menus.menu.notifications.label": "#c4a7e7",
        "theme.bar.menus.menu.power.buttons.sleep.icon": "#2a273f",
        "theme.bar.menus.menu.power.buttons.sleep.text": "#9ccfd8",
        "theme.bar.menus.menu.power.buttons.sleep.icon_background": "#9ccfd8",
        "theme.bar.menus.menu.power.buttons.sleep.background": "#2a283e",
        "theme.bar.menus.menu.power.buttons.logout.icon": "#2a273f",
        "theme.bar.menus.menu.power.buttons.logout.text": "#9ccfd8",
        "theme.bar.menus.menu.power.buttons.logout.icon_background": "#9ccfd8",
        "theme.bar.menus.menu.power.buttons.logout.background": "#2a283e",
        "theme.bar.menus.menu.power.buttons.restart.icon": "#2a273f",
        "theme.bar.menus.menu.power.buttons.restart.text": "#f6c177",
        "theme.bar.menus.menu.power.buttons.restart.icon_background": "#f6c177",
        "theme.bar.menus.menu.power.buttons.restart.background": "#2a283e",
        "theme.bar.menus.menu.power.buttons.shutdown.icon": "#2a273f",
        "theme.bar.menus.menu.power.buttons.shutdown.text": "#eb6f92",
        "theme.bar.menus.menu.power.buttons.shutdown.icon_background": "#eb6f92",
        "theme.bar.menus.menu.power.buttons.shutdown.background": "#2a283e",
        "theme.bar.menus.menu.power.border.color": "#2a273f",
        "theme.bar.menus.menu.power.background.color": "#232136",
        "theme.bar.menus.menu.dashboard.monitors.disk.label": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.monitors.disk.bar": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.monitors.disk.icon": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.monitors.gpu.label": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.monitors.gpu.bar": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.monitors.gpu.icon": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.monitors.ram.label": "#f6c177",
        "theme.bar.menus.menu.dashboard.monitors.ram.bar": "#f6c177",
        "theme.bar.menus.menu.dashboard.monitors.ram.icon": "#f6c177",
        "theme.bar.menus.menu.dashboard.monitors.cpu.label": "#eb6f92",
        "theme.bar.menus.menu.dashboard.monitors.cpu.bar": "#eb6f92",
        "theme.bar.menus.menu.dashboard.monitors.cpu.icon": "#eb6f92",
        "theme.bar.menus.menu.dashboard.monitors.bar_background": "#393552",
        "theme.bar.menus.menu.dashboard.directories.right.bottom.color": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.directories.right.middle.color": "#3e8eb0",
        "theme.bar.menus.menu.dashboard.directories.right.top.color": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.directories.left.bottom.color": "#eb6f92",
        "theme.bar.menus.menu.dashboard.directories.left.middle.color": "#f6c177",
        "theme.bar.menus.menu.dashboard.directories.left.top.color": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.controls.input.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.controls.input.background": "#3e8eb0",
        "theme.bar.menus.menu.dashboard.controls.volume.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.controls.volume.background": "#eb6f92",
        "theme.bar.menus.menu.dashboard.controls.notifications.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.controls.notifications.background": "#f6c177",
        "theme.bar.menus.menu.dashboard.controls.bluetooth.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.controls.bluetooth.background": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.controls.wifi.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.controls.wifi.background": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.controls.disabled": "#44415a",
        "theme.bar.menus.menu.dashboard.shortcuts.recording": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.shortcuts.text": "#2a273f",
        "theme.bar.menus.menu.dashboard.shortcuts.background": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.button_text": "#232136",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.deny": "#eb6f92",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.confirm": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.body": "#e0def4",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.label": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.border": "#2a273f",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.background": "#232136",
        "theme.bar.menus.menu.dashboard.powermenu.confirmation.card": "#2a283e",
        "theme.bar.menus.menu.dashboard.powermenu.sleep": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.powermenu.logout": "#9ccfd8",
        "theme.bar.menus.menu.dashboard.powermenu.restart": "#f6c177",
        "theme.bar.menus.menu.dashboard.powermenu.shutdown": "#eb6f92",
        "theme.bar.menus.menu.dashboard.profile.name": "#c4a7e7",
        "theme.bar.menus.menu.dashboard.border.color": "#2a273f",
        "theme.bar.menus.menu.dashboard.background.color": "#232136",
        "theme.bar.menus.menu.dashboard.card.color": "#2a283e",
        "theme.bar.menus.menu.clock.weather.hourly.temperature": "#c4a7e7",
        "theme.bar.menus.menu.clock.weather.hourly.icon": "#c4a7e7",
        "theme.bar.menus.menu.clock.weather.hourly.time": "#c4a7e7",
        "theme.bar.menus.menu.clock.weather.thermometer.extremelycold": "#9ccfd8",
        "theme.bar.menus.menu.clock.weather.thermometer.cold": "#3e8fb0",
        "theme.bar.menus.menu.clock.weather.thermometer.moderate": "#c4a7e7",
        "theme.bar.menus.menu.clock.weather.thermometer.hot": "#f6c177",
        "theme.bar.menus.menu.clock.weather.thermometer.extremelyhot": "#eb6f92",
        "theme.bar.menus.menu.clock.weather.stats": "#c4a7e7",
        "theme.bar.menus.menu.clock.weather.status": "#9ccfd8",
        "theme.bar.menus.menu.clock.weather.temperature": "#e0def4",
        "theme.bar.menus.menu.clock.weather.icon": "#c4a7e7",
        "theme.bar.menus.menu.clock.calendar.contextdays": "#44415a",
        "theme.bar.menus.menu.clock.calendar.days": "#e0def4",
        "theme.bar.menus.menu.clock.calendar.currentday": "#c4a7e7",
        "theme.bar.menus.menu.clock.calendar.paginator": "#c4a7e7",
        "theme.bar.menus.menu.clock.calendar.weekdays": "#c4a7e7",
        "theme.bar.menus.menu.clock.calendar.yearmonth": "#9ccfd8",
        "theme.bar.menus.menu.clock.time.timeperiod": "#9ccfd8",
        "theme.bar.menus.menu.clock.time.time": "#c4a7e7",
        "theme.bar.menus.menu.clock.text": "#e0def4",
        "theme.bar.menus.menu.clock.border.color": "#2a273f",
        "theme.bar.menus.menu.clock.background.color": "#232136",
        "theme.bar.menus.menu.clock.card.color": "#2a283e",
        "theme.bar.menus.menu.battery.slider.puck": "#393552",
        "theme.bar.menus.menu.battery.slider.backgroundhover": "#393552",
        "theme.bar.menus.menu.battery.slider.background": "#44415a",
        "theme.bar.menus.menu.battery.slider.primary": "#f6c177",
        "theme.bar.menus.menu.battery.icons.active": "#f6c177",
        "theme.bar.menus.menu.battery.icons.passive": "#56526e",
        "theme.bar.menus.menu.battery.listitems.active": "#f6c177",
        "theme.bar.menus.menu.battery.listitems.passive": "#e0def4",
        "theme.bar.menus.menu.battery.text": "#e0def4",
        "theme.bar.menus.menu.battery.label.color": "#f6c177",
        "theme.bar.menus.menu.battery.border.color": "#2a273f",
        "theme.bar.menus.menu.battery.background.color": "#232136",
        "theme.bar.menus.menu.battery.card.color": "#2a283e",
        "theme.bar.menus.menu.systray.dropdownmenu.divider": "#2a283e",
        "theme.bar.menus.menu.systray.dropdownmenu.text": "#e0def4",
        "theme.bar.menus.menu.systray.dropdownmenu.background": "#232136",
        "theme.bar.menus.menu.bluetooth.iconbutton.active": "#9ccfd8",
        "theme.bar.menus.menu.bluetooth.iconbutton.passive": "#e0def4",
        "theme.bar.menus.menu.bluetooth.icons.active": "#9ccfd8",
        "theme.bar.menus.menu.bluetooth.icons.passive": "#56526e",
        "theme.bar.menus.menu.bluetooth.listitems.active": "#9ccfd8",
        "theme.bar.menus.menu.bluetooth.listitems.passive": "#e0def4",
        "theme.bar.menus.menu.bluetooth.switch.puck": "#393552",
        "theme.bar.menus.menu.bluetooth.switch.disabled": "#2a273f",
        "theme.bar.menus.menu.bluetooth.switch.enabled": "#9ccfd8",
        "theme.bar.menus.menu.bluetooth.switch_divider": "#393552",
        "theme.bar.menus.menu.bluetooth.status": "#393552",
        "theme.bar.menus.menu.bluetooth.text": "#e0def4",
        "theme.bar.menus.menu.bluetooth.label.color": "#9ccfd8",
        "theme.bar.menus.menu.bluetooth.border.color": "#2a273f",
        "theme.bar.menus.menu.bluetooth.background.color": "#232136",
        "theme.bar.menus.menu.bluetooth.card.color": "#2a283e",
        "theme.bar.menus.menu.network.iconbuttons.active": "#c4a7e7",
        "theme.bar.menus.menu.network.iconbuttons.passive": "#e0def4",
        "theme.bar.menus.menu.network.icons.active": "#c4a7e7",
        "theme.bar.menus.menu.network.icons.passive": "#56526e",
        "theme.bar.menus.menu.network.listitems.active": "#c4a7e7",
        "theme.bar.menus.menu.network.listitems.passive": "#e0def4",
        "theme.bar.menus.menu.network.status.color": "#393552",
        "theme.bar.menus.menu.network.text": "#e0def4",
        "theme.bar.menus.menu.network.label.color": "#c4a7e7",
        "theme.bar.menus.menu.network.border.color": "#2a273f",
        "theme.bar.menus.menu.network.background.color": "#232136",
        "theme.bar.menus.menu.network.card.color": "#2a283e",
        "theme.bar.menus.menu.volume.input_slider.puck": "#44415a",
        "theme.bar.menus.menu.volume.input_slider.backgroundhover": "#393552",
        "theme.bar.menus.menu.volume.input_slider.background": "#44415a",
        "theme.bar.menus.menu.volume.input_slider.primary": "#eb6f92",
        "theme.bar.menus.menu.volume.audio_slider.puck": "#44415a",
        "theme.bar.menus.menu.volume.audio_slider.backgroundhover": "#393552",
        "theme.bar.menus.menu.volume.audio_slider.background": "#44415a",
        "theme.bar.menus.menu.volume.audio_slider.primary": "#eb6f92",
        "theme.bar.menus.menu.volume.icons.active": "#eb6f92",
        "theme.bar.menus.menu.volume.icons.passive": "#56526e",
        "theme.bar.menus.menu.volume.iconbutton.active": "#eb6f92",
        "theme.bar.menus.menu.volume.iconbutton.passive": "#e0def4",
        "theme.bar.menus.menu.volume.listitems.active": "#eb6f92",
        "theme.bar.menus.menu.volume.listitems.passive": "#e0def4",
        "theme.bar.menus.menu.volume.text": "#e0def4",
        "theme.bar.menus.menu.volume.label.color": "#eb6f92",
        "theme.bar.menus.menu.volume.border.color": "#2a273f",
        "theme.bar.menus.menu.volume.background.color": "#232136",
        "theme.bar.menus.menu.volume.card.color": "#2a283e",
        "theme.bar.menus.menu.media.slider.puck": "#393552",
        "theme.bar.menus.menu.media.slider.backgroundhover": "#393552",
        "theme.bar.menus.menu.media.slider.background": "#44415a",
        "theme.bar.menus.menu.media.slider.primary": "#c4a7e7",
        "theme.bar.menus.menu.media.buttons.text": "#232136",
        "theme.bar.menus.menu.media.buttons.background": "#c4a7e7",
        "theme.bar.menus.menu.media.buttons.enabled": "#9ccfd8",
        "theme.bar.menus.menu.media.buttons.inactive": "#44415a",
        "theme.bar.menus.menu.media.border.color": "#2a273f",
        "theme.bar.menus.menu.media.card.color": "#2a283e",
        "theme.bar.menus.menu.media.background.color": "#232136",
        "theme.bar.menus.menu.media.album": "#c4a7e7",
        "theme.bar.menus.menu.media.artist": "#9ccfd8",
        "theme.bar.menus.menu.media.song": "#c4a7e7",
        "theme.bar.menus.tooltip.text": "#e0def4",
        "theme.bar.menus.tooltip.background": "#232136",
        "theme.bar.menus.dropdownmenu.divider": "#2a283e",
        "theme.bar.menus.dropdownmenu.text": "#e0def4",
        "theme.bar.menus.dropdownmenu.background": "#232136",
        "theme.bar.menus.slider.puck": "#393552",
        "theme.bar.menus.slider.backgroundhover": "#393552",
        "theme.bar.menus.slider.background": "#44415a",
        "theme.bar.menus.slider.primary": "#c4a7e7",
        "theme.bar.menus.progressbar.background": "#393552",
        "theme.bar.menus.progressbar.foreground": "#c4a7e7",
        "theme.bar.menus.iconbuttons.active": "#c4a7e7",
        "theme.bar.menus.iconbuttons.passive": "#e0def4",
        "theme.bar.menus.buttons.text": "#2a273f",
        "theme.bar.menus.buttons.disabled": "#44415a",
        "theme.bar.menus.buttons.active": "#c4a7e7",
        "theme.bar.menus.buttons.default": "#c4a7e7",
        "theme.bar.menus.check_radio_button.active": "#c4a7e7",
        "theme.bar.menus.check_radio_button.background": "#393452",
        "theme.bar.menus.switch.puck": "#393552",
        "theme.bar.menus.switch.disabled": "#2a273f",
        "theme.bar.menus.switch.enabled": "#c4a7e7",
        "theme.bar.menus.icons.active": "#c4a7e7",
        "theme.bar.menus.icons.passive": "#44415a",
        "theme.bar.menus.listitems.active": "#c4a7e7",
        "theme.bar.menus.listitems.passive": "#e0def4",
        "theme.bar.menus.popover.border": "#2a273f",
        "theme.bar.menus.popover.background": "#2a273f",
        "theme.bar.menus.popover.text": "#c4a7e7",
        "theme.bar.menus.label": "#c4a7e7",
        "theme.bar.menus.feinttext": "#2a273f",
        "theme.bar.menus.dimtext": "#44415a",
        "theme.bar.menus.text": "#e0def4",
        "theme.bar.menus.border.color": "#2a273f",
        "theme.bar.menus.cards": "#2a283e",
        "theme.bar.menus.background": "#232136",
        "theme.bar.buttons.modules.power.icon_background": "#eb6f92",
        "theme.bar.buttons.modules.power.icon": "#181825",
        "theme.bar.buttons.modules.power.background": "#2a283e",
        "theme.bar.buttons.modules.weather.icon_background": "#c4a7e7",
        "theme.bar.buttons.modules.weather.icon": "#2a283e",
        "theme.bar.buttons.modules.weather.text": "#c4a7e7",
        "theme.bar.buttons.modules.weather.background": "#2a283e",
        "theme.bar.buttons.modules.updates.icon_background": "#3e8eb0",
        "theme.bar.buttons.modules.updates.icon": "#181825",
        "theme.bar.buttons.modules.updates.text": "#3e8eb0",
        "theme.bar.buttons.modules.updates.background": "#2a283e",
        "theme.bar.buttons.modules.kbLayout.icon_background": "#9ccfd8",
        "theme.bar.buttons.modules.kbLayout.icon": "#181825",
        "theme.bar.buttons.modules.kbLayout.text": "#9ccfd8",
        "theme.bar.buttons.modules.kbLayout.background": "#2a283e",
        "theme.bar.buttons.modules.netstat.icon_background": "#9ccfd8",
        "theme.bar.buttons.modules.netstat.icon": "#181825",
        "theme.bar.buttons.modules.netstat.text": "#9ccfd8",
        "theme.bar.buttons.modules.netstat.background": "#2a283e",
        "theme.bar.buttons.modules.storage.icon_background": "#eb6f92",
        "theme.bar.buttons.modules.storage.icon": "#181825",
        "theme.bar.buttons.modules.storage.text": "#eb6f92",
        "theme.bar.buttons.modules.storage.background": "#2a283e",
        "theme.bar.buttons.modules.cpu.icon_background": "#eb6f92",
        "theme.bar.buttons.modules.cpu.icon": "#181825",
        "theme.bar.buttons.modules.cpu.text": "#eb6f92",
        "theme.bar.buttons.modules.cpu.background": "#2a283e",
        "theme.bar.buttons.modules.ram.icon_background": "#f6c177",
        "theme.bar.buttons.modules.ram.icon": "#181825",
        "theme.bar.buttons.modules.ram.text": "#f6c177",
        "theme.bar.buttons.modules.ram.background": "#2a283e",
        "theme.bar.buttons.notifications.total": "#c4a7e7",
        "theme.bar.buttons.notifications.icon_background": "#c4a7e7",
        "theme.bar.buttons.notifications.icon": "#2a283e",
        "theme.bar.buttons.notifications.background": "#2a283e",
        "theme.bar.buttons.clock.icon_background": "#c4a7e7",
        "theme.bar.buttons.clock.icon": "#2a283e",
        "theme.bar.buttons.clock.text": "#c4a7e7",
        "theme.bar.buttons.clock.background": "#2a283e",
        "theme.bar.buttons.battery.icon_background": "#f6c177",
        "theme.bar.buttons.battery.icon": "#2a283e",
        "theme.bar.buttons.battery.text": "#f6c177",
        "theme.bar.buttons.battery.background": "#2a283e",
        "theme.bar.buttons.systray.background": "#2a283e",
        "theme.bar.buttons.bluetooth.icon_background": "#9ccfd8",
        "theme.bar.buttons.bluetooth.icon": "#2a283e",
        "theme.bar.buttons.bluetooth.text": "#9ccfd8",
        "theme.bar.buttons.bluetooth.background": "#2a283e",
        "theme.bar.buttons.network.icon_background": "#c4a7e7",
        "theme.bar.buttons.network.icon": "#2a283e",
        "theme.bar.buttons.network.text": "#c4a7e7",
        "theme.bar.buttons.network.background": "#2a283e",
        "theme.bar.buttons.volume.icon_background": "#eb6f92",
        "theme.bar.buttons.volume.icon": "#2a283e",
        "theme.bar.buttons.volume.text": "#eb6f92",
        "theme.bar.buttons.volume.background": "#2a283e",
        "theme.bar.buttons.media.icon_background": "#c4a7e7",
        "theme.bar.buttons.media.icon": "#2a283e",
        "theme.bar.buttons.media.text": "#c4a7e7",
        "theme.bar.buttons.media.background": "#2a283e",
        "theme.bar.buttons.windowtitle.icon_background": "#c4a7e7",
        "theme.bar.buttons.windowtitle.icon": "#2a283e",
        "theme.bar.buttons.windowtitle.text": "#c4a7e7",
        "theme.bar.buttons.windowtitle.background": "#2a283e",
        "theme.bar.buttons.workspaces.numbered_active_underline_color": "#c678dd",
        "theme.bar.buttons.workspaces.numbered_active_highlighted_text_color": "#181825",
        "theme.bar.buttons.workspaces.active": "#c4a7e7",
        "theme.bar.buttons.workspaces.occupied": "#eb6f92",
        "theme.bar.buttons.workspaces.available": "#9ccfd8",
        "theme.bar.buttons.workspaces.hover": "#c4a7e7",
        "theme.bar.buttons.workspaces.background": "#2a283e",
        "theme.bar.buttons.dashboard.icon": "#9ccfd8",
        "theme.bar.buttons.dashboard.background": "#202138",
        "theme.bar.buttons.icon": "#242438",
        "theme.bar.buttons.text": "#c4a7e7",
        "theme.bar.buttons.hover": "#393552",
        "theme.bar.buttons.icon_background": "#c4a7e7",
        "theme.bar.buttons.background": "#2a283e",
        "theme.bar.buttons.style": "split",
        "theme.bar.background": "#232136",
        "theme.osd.label": "#c4a7e7",
        "theme.osd.icon": "#232136",
        "theme.osd.bar_overflow_color": "#eb6f92",
        "theme.osd.bar_empty_color": "#2a273f",
        "theme.osd.bar_color": "#c4a7e7",
        "theme.osd.icon_container": "#c4a7e7",
        "theme.osd.bar_container": "#232136",
        "theme.notification.close_button.label": "#232136",
        "theme.notification.close_button.background": "#eb6f92",
        "theme.notification.labelicon": "#c4a7e7",
        "theme.notification.text": "#e0def4",
        "theme.notification.time": "#56526e",
        "theme.notification.border": "#2a273f",
        "theme.notification.label": "#c4a7e7",
        "theme.notification.actions.text": "#2a273f",
        "theme.notification.actions.background": "#c4a7e7",
        "theme.notification.background": "#2a273f",
        "theme.bar.buttons.modules.power.border": "#eb6f92",
        "theme.bar.buttons.modules.weather.border": "#c4a7e7",
        "theme.bar.buttons.modules.updates.border": "#30738f",
        "theme.bar.buttons.modules.kbLayout.border": "#9ccfd8",
        "theme.bar.buttons.modules.netstat.border": "#9ccfd8",
        "theme.bar.buttons.modules.storage.border": "#eb6f92",
        "theme.bar.buttons.modules.cpu.border": "#eb6f92",
        "theme.bar.buttons.modules.ram.border": "#f6c177",
        "theme.bar.buttons.notifications.border": "#c4a7e7",
        "theme.bar.buttons.clock.border": "#c4a7e7",
        "theme.bar.buttons.battery.border": "#f6c177",
        "theme.bar.buttons.systray.border": "#26233a",
        "theme.bar.buttons.bluetooth.border": "#9ccfd8",
        "theme.bar.buttons.network.border": "#c4a7e7",
        "theme.bar.buttons.volume.border": "#eb6f92",
        "theme.bar.buttons.media.border": "#c4a7e7",
        "theme.bar.buttons.windowtitle.border": "#c4a7e7",
        "theme.bar.buttons.workspaces.border": "#1f1d2e",
        "theme.bar.buttons.dashboard.border": "#f6c177",
        "theme.bar.buttons.modules.submap.background": "#2a283e",
        "theme.bar.buttons.modules.submap.text": "#9ccfd8",
        "theme.bar.buttons.modules.submap.border": "#9ccfd8",
        "theme.bar.buttons.modules.submap.icon": "#181825",
        "theme.bar.buttons.modules.submap.icon_background": "#9ccfd8",
        "theme.bar.menus.menu.network.switch.enabled": "#c4a7e7",
        "theme.bar.menus.menu.network.switch.disabled": "#2a273f",
        "theme.bar.menus.menu.network.switch.puck": "#393552",
        "theme.bar.buttons.systray.customIcon": "#e0def4",
        "theme.bar.border.color": "#c4a7e7",
        "theme.bar.menus.menu.media.timestamp": "#e0def4",
        "theme.bar.buttons.borderColor": "#c4a7e7",
        "theme.bar.buttons.modules.hyprsunset.icon": "#181825",
        "theme.bar.buttons.modules.hyprsunset.background": "#2a283e",
        "theme.bar.buttons.modules.hyprsunset.icon_background": "#f6c177",
        "theme.bar.buttons.modules.hyprsunset.text": "#f6c177",
        "theme.bar.buttons.modules.hyprsunset.border": "#f6c177",
        "theme.bar.buttons.modules.hypridle.icon": "#181825",
        "theme.bar.buttons.modules.hypridle.background": "#2a283e",
        "theme.bar.buttons.modules.hypridle.icon_background": "#eb6f92",
        "theme.bar.buttons.modules.hypridle.text": "#eb6f92",
        "theme.bar.buttons.modules.hypridle.border": "#eb6f92",
        "theme.bar.menus.menu.network.scroller.color": "#c4a7e7",
        "theme.bar.menus.menu.bluetooth.scroller.color": "#9ccfd8",
        "theme.bar.buttons.modules.cava.text": "#9ccfd8",
        "theme.bar.buttons.modules.cava.background": "#2a283e",
        "theme.bar.buttons.modules.cava.icon_background": "#9ccfd8",
        "theme.bar.buttons.modules.cava.icon": "#181825",
        "theme.bar.buttons.modules.cava.border": "#9ccfd8",
        "theme.bar.scaling": 100,
        "theme.bar.menus.menu.volume.scaling": 100,
        "theme.tooltip.scaling": 100,
        "theme.bar.menus.popover.scaling": 100,
        "scalingPriority": "hyprland",
        "theme.bar.location": "top",
        "bar.launcher.icon": "",
        "bar.launcher.autoDetectIcon": true,
        "bar.workspaces.show_numbered": false,
        "bar.workspaces.monitorSpecific": false,
        "bar.network.showWifiInfo": true,
        "bar.battery.label": false,
        "menus.clock.weather.enabled": true,
        "menus.clock.weather.location": "Riyadh",
        "theme.bar.transparent": true,
        "menus.power.showLabel": true,
        "theme.bar.buttons.modules.kbLayout.enableBorder": false,
        "theme.bar.buttons.modules.updates.enableBorder": false,
        "theme.bar.buttons.modules.storage.enableBorder": false,
        "theme.bar.floating": false,
        "theme.bar.menus.menu.battery.scaling": 100,
        "theme.notification.scaling": 100,
        "theme.bar.menus.menu.dashboard.confirmation_scaling": 100,
        "theme.bar.menus.menu.power.scaling": 80,
        "menus.dashboard.shortcuts.left.shortcut3.command": "vesktop",
        "menus.dashboard.shortcuts.left.shortcut3.tooltip": "vesktop",
        "menus.dashboard.shortcuts.left.shortcut1.icon": "󰈹",
        "menus.dashboard.shortcuts.left.shortcut1.command": "firefox",
        "menus.dashboard.shortcuts.left.shortcut1.tooltip": "firefox",
        "menus.dashboard.shortcuts.left.shortcut2.command": "steam",
        "menus.dashboard.shortcuts.left.shortcut2.tooltip": "steam",
        "menus.dashboard.stats.interval": 2500,
        "menus.dashboard.directories.left.directory1.command": "bash -c \"xdg-open $HOME/zaneyos/\"",
        "menus.dashboard.directories.left.directory1.label": " git repo",
        "bar.workspaces.workspaceMask": true,
        "bar.workspaces.showWsIcons": true,
        "bar.workspaces.numbered_active_indicator": "color",
        "theme.bar.buttons.workspaces.smartHighlight": true,
        "notifications.monitor": 0,
        "theme.bar.menus.menu.bluetooth.scaling": 100,
        "menus.dashboard.shortcuts.left.shortcut2.icon": "󰓓",
        "theme.osd.location": "right",
        "menus.media.displayTime": false,
        "menus.media.hideAuthor": false,
        "bar.layouts": {
          "0": {
            "left": [
              "dashboard",
              "media",
              "cava",
              "windowtitle"
            ],
            "middle": [
              "workspaces"
            ],
            "right": [
              "volume",
              "network",
              "bluetooth",
              "systray",
              "clock",
              "notifications"
            ]
          },
          "1": {
            "left": [
              "dashboard",
              "workspaces",
              "windowtitle"
            ],
            "middle": [
              "media"
            ],
            "right": [
              "volume",
              "clock",
              "notifications"
            ]
          },
          "2": {
            "left": [
              "dashboard",
              "workspaces",
              "windowtitle"
            ],
            "middle": [
              "media"
            ],
            "right": [
              "volume",
              "clock",
              "notifications"
            ]
          }
        },
        "theme.bar.border.location": "none",
        "bar.workspaces.showApplicationIcons": true,
        "bar.workspaces.applicationIconOncePerWorkspace": false,
        "bar.workspaces.showAllActive": false,
        "bar.clock.format": "%a %b %d %H:%M:%S",
        "theme.bar.menus.menu.notifications.scaling": 100,
        "theme.bar.menus.menu.clock.scaling": 100,
        "bar.customModules.storage.labelType": "free",
        "bar.customModules.storage.pollingInterval": 100,
        "bar.customModules.netstat.pollingInterval": 100,
        "bar.clock.icon": "󰸗",
        "bar.clock.showIcon": false,
        "bar.workspaces.workspaces": 6,
        "theme.bar.buttons.dashboard.enableBorder": false,
        "bar.launcher.middleClick": "rofi -show drun",
        "bar.clock.showTime": true,
        "bar.customModules.cava.bars": 12,
        "bar.customModules.cava.showIcon": false,
        "bar.customModules.cava.icon": "",
        "bar.customModules.cava.channels": 0,
        "menus.volume.raiseMaximumVolume": true,
        "theme.bar.opacity": 100,
        "theme.bar.buttons.opacity": 95,
        "menus.clock.weather.key": "074605ce76bf42a1837100615252301",
        "menus.clock.weather.unit": "metric",
        "bar.customModules.netstat.rateUnit": "auto",
        "bar.customModules.kbLayout.labelType": "code",
        "theme.font.name": "Noto Sans CJK JP",
        "theme.font.style": "italic",
        "theme.font.label": "Noto Sans CJK JP Bold Italic",
        "menus.transition": "crossfade",
        "wallpaper.image": "",
        "wallpaper.pywal": false,
        "theme.bar.buttons.media.enableBorder": false,
        "bar.windowtitle.rightClick": "",
        "wallpaper.enable": false,
        "theme.bar.border.width": "0.15em",
        "theme.bar.buttons.enableBorders": false,
        "hyprpanel.restartAgs": true,
        "theme.matugen_settings.mode": "dark",
        "theme.matugen_settings.scheme_type": "tonal-spot",
        "theme.matugen_settings.variation": "standard_1",
        "theme.bar.buttons.background_opacity": 100,
        "theme.bar.buttons.notifications.enableBorder": false,
        "menus.transitionTime": 200,
        "theme.bar.buttons.modules.microphone.border": "#9ccfd8",
        "theme.bar.buttons.modules.microphone.background": "#2a283e",
        "theme.bar.buttons.modules.microphone.text": "#9ccfd8",
        "theme.bar.buttons.modules.microphone.icon": "#2a283e",
        "theme.bar.buttons.modules.microphone.icon_background": "#9ccfd8",
        "theme.bar.enableShadow": false,
        "theme.bar.buttons.notifications.hover": "#504945",
        "theme.bar.buttons.clock.hover": "#504945",
        "theme.bar.buttons.battery.hover": "#504945",
        "theme.bar.buttons.systray.hover": "#504945",
        "theme.bar.buttons.bluetooth.hover": "#504945",
        "theme.bar.buttons.network.hover": "#504945",
        "theme.bar.buttons.volume.hover": "#504945",
        "theme.bar.buttons.media.hover": "#504945",
        "theme.bar.buttons.windowtitle.hover": "#504945",
        "theme.bar.buttons.workspaces.numbered_active_text_color": "#24283b",
        "theme.bar.buttons.dashboard.hover": "#504945",
        "theme.bar.menus.menu.power.card.color": "#2a283e",
        "theme.bar.buttons.modules.cpu.hover": "#45475a",
        "theme.bar.buttons.volume.output_icon": "#11111b",
        "theme.bar.buttons.volume.output_text": "#eba0ac",
        "theme.bar.buttons.volume.input_icon": "#11111b",
        "theme.bar.buttons.volume.input_text": "#eba0ac",
        "theme.bar.buttons.volume.separator": "#45475a",
        "theme.bar.buttons.modules.cpuTemp.icon_background": "#fab387",
        "theme.bar.buttons.modules.cpuTemp.icon": "#181824",
        "theme.bar.buttons.modules.cpuTemp.text": "#fab387",
        "theme.bar.buttons.modules.cpuTemp.border": "#fab387",
        "theme.osd.border.color": "#8ff0a4",
        "bar.customModules.storage.paths": [
          "/"
        ]
      }
    '';
    force = true;
  }; # See https://mynixos.com/home-manager/option/home.activation
  home.activation.linktoHyprpanelConfig1 = lib.hm.dag.entryAfter ["writeBoundary"] ''
    $DRY_RUN_CMD rm -f $HOME/.config/hyprpanel/config.json
    $DRY_RUN_CMD ln -sf $HOME/.config/hyprpanel/config1.json $HOME/.config/hyprpanel/config.json
  '';
}
